[tasks.frontend-copy-bench]
description = "Copy generated bench files"
category = "Docs"
command = "cp"
args = ["-r", "target/criterion", "docs/benches/"]

[tasks.frontend-copy-docs]
description = "Copy generated doc files"
category = "Docs"
command = "cp"
args = ["-r", "target/doc", "docs/doc/"]

[tasks.frontend]
description = "Copy generated files"
category = "Docs"
run_task = [
    { name = "frontend-copy-bench" },
    { name = "frontend-copy-docs" }
]

[tasks.docs]
description = "Build docs"
category = "Documentation"
command = "cargo"
args = ["doc", "--no-deps"]

[tasks.bench]
description = "Run benchmarks"
category = "Test"
command = "cargo"
args = ["bench"]

[tasks.test]
description = "Run tests"
category = "Test"
command = "cargo"
args = ["test"]

[tasks.build]
description = "Runs the rust compiler."
category = "Build"
command = "cargo"
args = ["build", "--all-features"]